<?php

/* 
 * Tell static about all esi links..'
 */

/**
 * Have static generate files without .html extension as this is what
 * the esi path is expecting. This works since they aren'te html pages.
 */
function static_esi_static_filename_alter(&$filename, $info) {
  if (strpos($filename, 'esi/') === 0) {
    $filename = $info['alias'];
  }
}

/**
 * Implements hook_esi_block_url_alter(&$url)
 */
function static_esi_esi_block_url_alter(&$url) {
  // Since we don't have querystrings, roles or users on a static site,
  // we don't need those parts in the url.
  $parts = explode('/', $url);
  unset($parts[3]);
  unset($parts[4]);
  unset($parts[5]);
  $url = implode('/', $parts);
  static_track_paths(
    array(
      array(
        'path' => $url, 
        'dynamic' => 1,
      )
    )
  );
}

/**
 * Implements hook_context_block_url_alter(&$url)
 */
function static_esi_esi_context_url_alter($url) {
  // Since we don't have querystrings, roles or users on a static site,
  // we don't need those parts in the url.
  $parts = explode('/', $url);
  unset($parts[3]);
  unset($parts[4]);
  unset($parts[5]);
  $url = implode('/', $parts);
  static_track_paths(
    array(
      array(
        'path' => $url, 
        'dynamic' => 1,
      )
    )
  );
}

/**
 * Implements hook_panels_block_url_alter(&$url)
 */
function static_esi_esi_panels_url_alter($url) {
  // TODO: Do we need to do something to the url to simplify it?
  static_track_paths(array($url));
}

/**
 * Implements hook_static_refresh_paths().
 * Refresh all paths for the static module.
 */
function static_esi_static_refresh_paths() {
  // Not sure what to do here or if this is necessary. As pages are being
  // generated all links should be captured by the above hooks.
  return array();
}

// Need more ways to clear the esi static cache files.
// Views blocks
// Panel blocks
// Other module blocks
// Perhaps just set them to refresh on cron every 15 minutes?

/**
 * Implements hook_form_FORM_ID_alter
 */
function static_esi_form_block_admin_configure_alter(&$form, $form_state) {
  $form['#submit'][] = 'static_esi_block_admin_configure_form_submit';
}

/**
 * When a block is saved, clear the static cache for that block.
 */
function static_esi_block_admin_configure_form_submit($form, $form_state) {
  $block = block_load($form_state['values']['module'], $form_state['values']['delta']);
  $block->delta = esi_block__new_delta($form_state['values']['module'], $form_state['values']['delta']);
  static_set_expired(esi_block_url($block));
}