<?php

/**
 * @file
 * Integration between the static generator and the views module.
 */

/**
 * Implements hook_static_refresh_paths().
 *
 * Refresh all paths for the static module.
 */
function static_views_static_refresh_paths() {
  $paths = array();
  $views = views_get_all_views();
  foreach ($views as $view) {
    if (!$view->disabled) {
      foreach ($view->display as $id => $display) {
        if ($display->display_plugin == 'page' && strpos($display->display_options['path'], '%') === FALSE) {
          $paths[$display->display_options['path']] = array(
            'path' => $display->display_options['path'],
            'frequency' => 300,
          );
        }
      }
    }
  }
  return $paths;
}
