<?php

/**
 * @file
 * Integration between the static generator and the views module.
 */

/**
 * Implements hook_static_refresh_paths().
 *
 * Refresh all paths for the static module.
 */
function static_views_static_refresh_paths() {
  $paths = array();
  $views = views_get_all_views();
  foreach ($views as $view) {
    if (!$view->disabled) {
      foreach ($view->display as $id => $display) {
        if (in_array($display->display_plugin, array('page', 'feed')) && strpos($display->display_options['path'], '%') === FALSE) {
          $paths[$display->display_options['path']] = array(
            'path' => $display->display_options['path'],
            'frequency' => 300,
          );
        }
      }
    }
  }
  // Check access for anonymous to prevent adding admin pages.
  // Force the current user to anonymous to ensure consistent permissions.
  $original_user = $GLOBALS['user'];
  $GLOBALS['user'] = drupal_anonymous_user();

  foreach ($paths as $path => $info) {
    if ($router_item = menu_get_item($path)) {
      if (!$router_item['access']) {
        unset($paths[$path]);
      }
    }
  }

  // Restore the user.
  $GLOBALS['user'] = $original_user;

  return $paths;
}
